import os
from pathlib import Path
from datetime import datetime

def generate_index():
    interactive_dir = Path('interactive')
    html_files = []
    
    # Find all HTML files
    for html_file in interactive_dir.rglob('*.html'):
        if html_file.name != 'index.html':
            rel_path = html_file.relative_to(interactive_dir)
            # Get file modification time
            mtime = datetime.fromtimestamp(html_file.stat().st_mtime)
            
            # Parse directory structure for organization
            parts = rel_path.parts
            category = parts[0] if len(parts) > 1 else "Other"
            
            html_files.append({
                'path': str(rel_path),
                'name': html_file.stem.replace('_', ' ').title(),
                'category': category,
                'modified': mtime
            })
    
    # Sort by category and name
    html_files.sort(key=lambda x: (x['category'], x['name']))
    
    # Group by category
    categories = {}
    for file in html_files:
        cat = file['category']
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(file)
    
    # Generate HTML
    html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Katalog der interaktiven Assets</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
            max-width: 900px;
            margin: 50px auto;
            padding: 0 20px;
            background: #f5f5f5;
        }
        .header {
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 30px;
        }
        h1 {
            margin: 0 0 10px 0;
            color: #333;
        }
        .subtitle {
            color: #666;
            margin: 0;
        }
        .category {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }
        .category h2 {
            margin-top: 0;
            color: #0366d6;
            border-bottom: 2px solid #0366d6;
            padding-bottom: 10px;
        }
        .file-list {
            list-style: none;
            padding: 0;
        }
        .file-item {
            padding: 12px;
            border-bottom: 1px solid #eee;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .file-item:last-child {
            border-bottom: none;
        }
        .file-item:hover {
            background: #f9f9f9;
        }
        .file-link {
            color: #0366d6;
            text-decoration: none;
            font-weight: 500;
        }
        .file-link:hover {
            text-decoration: underline;
        }
        .file-meta {
            color: #666;
            font-size: 0.9em;
        }
        .updated {
            color: #999;
            font-size: 0.85em;
        }
        footer {
            text-align: center;
            margin-top: 40px;
            color: #999;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Katalog der interaktiven Assets</h1>
        <p class="updated">Last updated: """ + datetime.now().strftime('%Y-%m-%d %H:%M:%S') + """</p>
    </div>
"""
    
    for category, files in categories.items():
        html += f"""
    <div class="category">
        <h2>{category.replace('_', ' ').title()}</h2>
        <ul class="file-list">
"""
        for file in files:
            html += f"""
            <li class="file-item">
                <a href="{file['path']}" class="file-link" target="_blank">{file['name']}</a>
                <span class="file-meta">{file['modified'].strftime('%Y-%m-%d')}</span>
            </li>
"""
        html += """
        </ul>
    </div>
"""
    
    html += """
    <footer>
        Auto-generated by Script generate_index.py
    </footer>
</body>
</html>
"""
    
    # Write index.html
    index_path = interactive_dir / 'index.html'
    index_path.write_text(html, encoding='utf-8')
    print(f"✓ Generated index with {len(html_files)} files")

if __name__ == '__main__':
    generate_index()